version: '3.8'
name: ict-management
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    command: sleep infinity

    network_mode: service:db

  db:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ict-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb

volumes:
  ict-data: