"""initial migration

Revision ID: 5142797675de
Revises: 
Create Date: 2026-03-29 18:43:46.403489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5142797675de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # 1. Crear tabla users sin FK
  op.create_table('users',
  sa.Column('id', sa.String(length=36), primary_key=True),
  sa.Column('name', sa.String(length=80), nullable=False),
  sa.Column('email', sa.String(length=120), nullable=False, unique=True),
  sa.Column('password', sa.Text(), nullable=False),
  sa.Column('created_at', sa.DateTime(), nullable=True),
  sa.Column('updated_at', sa.DateTime(), nullable=True)
  )

  # 2. Crear tabla companies
  op.create_table('companies',
  sa.Column('id', sa.String(length=36), primary_key=True),
  sa.Column('name', sa.String(length=120), nullable=False),
  sa.Column('description', sa.Text(), nullable=False),
  sa.Column('owner_id', sa.String(length=36), nullable=False),
  sa.Column('created_at', sa.DateTime(), nullable=True),
  sa.Column('updated_at', sa.DateTime(), nullable=True),
  sa.ForeignKeyConstraint(['owner_id'], ['users.id'])
  )

  # 3. Agregar la FK de users a companies
  op.add_column('users', sa.Column('company_id', sa.String(length=36), nullable=True))
  op.create_foreign_key(
  "fk_users_company", "users", "companies", ["company_id"], ["id"]
  )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
