"""add softwares table

Revision ID: 63413f8c97b1
Revises: aea7f500bd10
Create Date: 2026-03-29 19:37:03.740866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63413f8c97b1'
down_revision = 'aea7f500bd10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('type', sa.Enum('laptop', 'desktop', 'server', 'tablet', 'smartphone', 'printer', 'camera', 'other'), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('active', 'inactive', 'maintenance'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('softwares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('pricing', sa.Float(), nullable=True),
    sa.Column('renew_date', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('support_contact', sa.String(length=80), nullable=True),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('users_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('softwares')
    op.drop_table('equipments')
    # ### end Alembic commands ###
